// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, url, secret, created_at
FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const insertEndpoint = `-- name: InsertEndpoint :exec
INSERT INTO endpoints(id, url, secret, created_at)
VALUES(gen_random_uuid(), $1, $2, NOW())
RETURNING id, url, secret, created_at
`

type InsertEndpointParams struct {
	Url    string `json:"url"`
	Secret string `json:"secret"`
}

func (q *Queries) InsertEndpoint(ctx context.Context, arg InsertEndpointParams) error {
	_, err := q.db.Exec(ctx, insertEndpoint, arg.Url, arg.Secret)
	return err
}
