// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec
INSERT INTO delivery_attempts (id, delivery_id, attempt_number, http_status, latency_ms, error, attempted_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type InsertDeliveryAttemptParams struct {
	ID            pgtype.UUID `json:"id"`
	DeliveryID    pgtype.UUID `json:"delivery_id"`
	AttemptNumber int32       `json:"attempt_number"`
	HttpStatus    pgtype.Int4 `json:"http_status"`
	LatencyMs     int32       `json:"latency_ms"`
	Error         pgtype.Text `json:"error"`
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.ID,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.Error,
	)
	return err
}
