// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingDeliveries = `-- name: ClaimPendingDeliveries :many
WITH selected AS (
    SELECT id, event_id, endpoint_id, status, attempt_count, max_attempts, next_attempt_at, created_at, updated_at FROM deliveries
    WHERE status = 'pending' AND next_attempt_at <= NOW()
    ORDER BY next_attempt_at ASC 
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE deliveries d
SET status = 'in_flight', updated_at = NOW()
FROM selected
WHERE d.id = selected.id
RETURNING
    d.id,
    d.event_id,
    d.endpoint_id,
    d.attempt_count,
    d.max_attempts
`

type ClaimPendingDeliveriesRow struct {
	ID           pgtype.UUID `json:"id"`
	EventID      pgtype.UUID `json:"event_id"`
	EndpointID   pgtype.UUID `json:"endpoint_id"`
	AttemptCount int32       `json:"attempt_count"`
	MaxAttempts  int32       `json:"max_attempts"`
}

func (q *Queries) ClaimPendingDeliveries(ctx context.Context) ([]ClaimPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDeliveriesRow
	for rows.Next() {
		var i ClaimPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO deliveries (id, event_id, endpoint_id, status, attempt_count, next_attempt_at, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', 0, NOW(), NOW(), NOW())
`

type InsertDeliveryParams struct {
	ID         pgtype.UUID `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery, arg.ID, arg.EventID, arg.EndpointID)
	return err
}

const markDead = `-- name: MarkDead :exec
UPDATE deliveries
    SET status = 'dead',
    attempt_count = attempt_count + 1,
    updated_at = NOW()
WHERE id = $1
`

// when attempt_count >= max_attempts, no more retries
func (q *Queries) MarkDead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDead, id)
	return err
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE deliveries
SET status = 'delivered', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDelivered, id)
	return err
}

const markFailedWithRetry = `-- name: MarkFailedWithRetry :exec
UPDATE deliveries
    SET status = 'pending',
    attempt_count = attempt_count + 1,
    next_attempt_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkFailedWithRetryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

// called after a failed attempt
func (q *Queries) MarkFailedWithRetry(ctx context.Context, arg MarkFailedWithRetryParams) error {
	_, err := q.db.Exec(ctx, markFailedWithRetry, arg.ID, arg.NextAttemptAt)
	return err
}
