// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingDeliveries = `-- name: ClaimPendingDeliveries :many
WITH selected AS (
    SELECT d.id FROM deliveries d
    WHERE d.status = 'pending' AND d.next_attempt_at <= NOW()
    ORDER BY d.next_attempt_at ASC
    LIMIT 50
    FOR UPDATE OF d SKIP LOCKED
)
UPDATE deliveries d
SET status = 'in_flight', updated_at = NOW()
FROM selected, events e, endpoints ep
WHERE d.id = selected.id
  AND e.id = d.event_id
  AND ep.id = d.endpoint_id
RETURNING
    d.id,
    d.event_id,
    d.endpoint_id,
    d.attempt_count,
    d.max_attempts,
    e.payload,
    ep.url,
    ep.secret
`

type ClaimPendingDeliveriesRow struct {
	ID           pgtype.UUID `json:"id"`
	EventID      pgtype.UUID `json:"event_id"`
	EndpointID   pgtype.UUID `json:"endpoint_id"`
	AttemptCount int32       `json:"attempt_count"`
	MaxAttempts  int32       `json:"max_attempts"`
	Payload      []byte      `json:"payload"`
	Url          string      `json:"url"`
	Secret       string      `json:"secret"`
}

func (q *Queries) ClaimPendingDeliveries(ctx context.Context) ([]ClaimPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDeliveriesRow
	for rows.Next() {
		var i ClaimPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.Payload,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO deliveries (id, event_id, endpoint_id, status, attempt_count, reap_count, next_attempt_at, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', 0, 0, NOW(), NOW(), NOW())
`

type InsertDeliveryParams struct {
	ID         pgtype.UUID `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery, arg.ID, arg.EventID, arg.EndpointID)
	return err
}

const markDead = `-- name: MarkDead :exec
UPDATE deliveries
    SET status = 'dead',
    attempt_count = attempt_count + 1,
    updated_at = NOW()
WHERE id = $1
`

// when attempt_count >= max_attempts, no more retries
func (q *Queries) MarkDead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDead, id)
	return err
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE deliveries
SET status = 'delivered', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDelivered, id)
	return err
}

const markFailedWithRetry = `-- name: MarkFailedWithRetry :exec
UPDATE deliveries
    SET status = 'pending',
    attempt_count = attempt_count + 1,
    next_attempt_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkFailedWithRetryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

// called after a failed attempt
func (q *Queries) MarkFailedWithRetry(ctx context.Context, arg MarkFailedWithRetryParams) error {
	_, err := q.db.Exec(ctx, markFailedWithRetry, arg.ID, arg.NextAttemptAt)
	return err
}

const reapStuckDeliveries = `-- name: ReapStuckDeliveries :exec
UPDATE deliveries
SET status = CASE
        WHEN reap_count + 1 >= $2 THEN 'dead'
        ELSE 'pending'
    END,
    reap_count = reap_count + 1,
    updated_at = NOW()
WHERE status = 'in_flight'
AND updated_at < $1
`

func (q *Queries) ReapStuckDeliveries(ctx context.Context, cutoff pgtype.Timestamptz, maxReaps int32) error {
	_, err := q.db.Exec(ctx, reapStuckDeliveries, cutoff, maxReaps)
	return err
}
