// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Delivery struct {
	ID            pgtype.UUID        `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	ReapCount     int32              `json:"reap_count"`
	MaxAttempts   int32              `json:"max_attempts"`
	Seq           int64              `json:"seq"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	DeliveryID    pgtype.UUID        `json:"delivery_id"`
	AttemptNumber int32              `json:"attempt_number"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	LatencyMs     int32              `json:"latency_ms"`
	Error         pgtype.Text        `json:"error"`
	AttemptedAt   pgtype.Timestamptz `json:"attempted_at"`
}

type Endpoint struct {
	ID        pgtype.UUID        `json:"id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	Sequence  int64              `json:"sequence"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID         pgtype.UUID        `json:"id"`
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
